### ISSUE TITLE
doesnt get default id virtual

### ISSUE THREAD

**Issue by fozzle** [vkarpov15/mongoose-lean-virtuals#1]
See title. Is this by design?

**Comment by fozzle** [comment]
found https://github.com/mongoosejs/mongoose-lean-id just gonna close this

**Comment by vkarpov15** [comment]
Opened up an issue :point_up: in mongoose to track. mongoose-lean-id is a very simplified version of this lib, works great if you only need id. This lib should be able to get the id virtual, if it doesn't that's a bug.

**Comment by vkarpov15** [comment]
So I added a test case for this and it looks like this plugin does get the id virtual, unless you explicitly turn it off. Can you please provide a code sample that reproduces your issue?
