### ISSUE TITLE
lean({virtuals: true}) doesn't work with mongoose discriminator

### ISSUE THREAD

**Issue by aviadhadidainx** [vkarpov15/mongoose-lean-virtuals#27]
When i have virtual on discriminator it doesn't return the virtuals on the result.
for example:
let's assume we have `BaseModel`.

The `DerivedModel `has virtual method called foo.

If we do `DerivedModel.find({}).lean({virtuals: true})` we will not get the foo property

**Comment by vkarpov15** [comment]
The below script works for me:

```javascript
const Model = mongoose.model('gh27', mongoose.Schema({ name: String }));
    const schema = mongoose.Schema({ test: String });
    schema.virtual('foo').get(() => 42);
    schema.plugin(mongooseLeanVirtuals);
    const D = Model.discriminator('gh27_test', schema);

    return co(function*() {
      yield D.create({ name: 'test' });

      const doc = yield D.findOne().lean({ virtuals: true });
      assert.equal(doc.foo, 42);
    });
```

Make sure that you apply this plugin to the discriminator schema, or set the [`applyPluginsToDiscriminators` option](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set)
