### ISSUE TITLE
Typescript: types conflict @types/mongoose

### ISSUE THREAD

**Issue by maxsh8x** [vkarpov15/mongoose-lean-virtuals#3]
![screenshot from 2017-08-25 11-17-14](https://user-images.githubusercontent.com/17633120/29706219-a8237a40-8989-11e7-9b64-918090cf2786.png)

**Comment by vkarpov15** [comment]
Sounds like an issue with your typescript bindings. Our docs do say that [lean() now accepts either a boolean or an object](https://github.com/Automattic/mongoose/blob/e5c9a6d80a849cb1377b87397f77c31aad5ab3ea/lib/query.js#L1113). Please open up an issue here: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by flyinghawker** [comment]
seems like the issue still exists in mongoose v5.4.19

>   /**
     * Sets the lean option.
     * Documents returned from queries with the lean option enabled are plain
     * javascript objects, not MongooseDocuments. They have no save method,
     * getters/setters or other Mongoose magic applied.
     * @param bool defaults to true
     */
    lean(bool?: boolean): Query<any> & QueryHelpers;

lean doesn't support object.

**Comment by vkarpov15** [comment]
@flyinghawker false: https://github.com/Automattic/mongoose/blob/5e47d8be8b35599e4997d5f2ef88ef19c7853a32/lib/query.js#L1597 . Either way, this isn't a typescript bindings repo, please open an issue there
