### ISSUE TITLE
No support for .parent() or .ownerDocument()?

### ISSUE THREAD

**Issue by jnardone** [vkarpov15/mongoose-lean-virtuals#40]
We have a virtual on a child schema that needs visibility to the parent document.

```
ChildSchema.virtual('hasAThing').get(function () {
  const parent = this.parent(); // fails!
  return parent.arrayOfThings.some(
    (thing) => thing.status === 'valid' and thing.items.includes(this._id)
  );
});

ParentSchema = new Schema(
{
   _id: { type: ObjectId, required: true },
   arrayOfThings: [ChildSchema]
});

ParentSchema.plugin(mongooseLeanVirtuals);
ParentSchema.set('toJSON', { virtuals: true });
ParentSchema.set('toObject', { virtuals: true });
```

I was hoping (expecting?) that the ability to see .parent() (or .ownerDocument()) from Mongoose would work here as documented in other places e.g. https://mongoosejs.com/docs/subdocs.html#subdoc-parents

But these are undefined.  Should they be?  Is there a way of accessing the parent document as part of leanvirtuals?

Stack trace that happens:

> Object.<anonymous> (/myProject/src/my.model.js:101:20)
>     at VirtualType.applyGetters (/myProject/src/node_modules/mongoose/lib/virtualtype.js:142:25)
>     at attachVirtualsToDoc (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:148:55)
>     at attachVirtualsToDoc (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:119:7)
>     at applyVirtualsToResult (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:78:7)
>     at model.Query.attachVirtuals (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:71:10)
>     at applyVirtualsToChildren (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:111:20)
>     at model.Query.attachVirtuals (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:70:3)
>     at model.Query.<anonymous> (/myProject/src/node_modules/mongoose-lean-virtuals/index.js:43:22)
>     at /myProject/src/node_modules/mongoose-lean-virtuals/index.js:11:12
> 
(the error occurs on the line where I attempt to call `.parent()` or `.ownerDocument()`)

How do I reference the parent document from a child virtual when using this library?

Mongoose ver 5.10.2
Mongoose-lean-virtuals ver 0.6.9

**Comment by vkarpov15** [comment]
The lack of `.parent()` is intentional. With [lean](https://mongoosejs.com/docs/tutorials/lean.html), you get a raw [POJO](https://masteringjs.io/tutorials/fundamentals/pojo) rather than a Mongoose document, so naturally it won't have a `parent()` function.

I think the way to go is for us to add a `parent()` function to the mongoose-lean-virtuals plugin, like `require('mongoose-lean-virtuals').parent(myObj)`, that allows you to get the parent. What do you think @jnardone ?

**Comment by jnardone** [comment]
Something like that would work here - as long as I can get some kind of context to call .parent and/or .ownerDocument for a given document.
