### ISSUE TITLE
Error in 0.7.0 - weakmap key error

### ISSUE THREAD

**Issue by jnardone** [vkarpov15/mongoose-lean-virtuals#41]
When upgrading to 0.7.0 I'm getting the following error due to

```
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at applyVirtualsToResult (/root/repo/node_modules/mongoose-lean-virtuals/index.js:88:28)
    at model.Query.attachVirtuals (/root/repo/node_modules/mongoose-lean-virtuals/index.js:80:10)
    at applyVirtualsToChildren (/root/repo/node_modules/mongoose-lean-virtuals/index.js:126:20)
```

```
      if (parent != null) {
        documentParentsMap.set(res[i], parent);
      }
```

Note that I was the asker for the `.parent` function, but this code is not yet using it.

The issue is that there are code paths where this could be called but there's no results.  E.g. the fix is to

```
      if (parent != null) {
          if (res[i]) {
            documentParentsMap.set(res[i], parent);
          }
      }
```

I confirmed with logging that sometimes res[i] is `undefined` and thus we need a truthy check.

**Comment by jnardone** [comment]
@vkarpov15 this is still a bit brittle.  Malformed data can easily break this - we have some test harnesses that put simple `numbers` in where values are declared as `ObjectId`.  I don't know if this should be more resilient or throw a better error message or what.  I was able to fix the test, but if `res[i]` is a non-object then this will continue to break.

**Comment by vkarpov15** [comment]
I'll add a check for that just in case. We hadn't thought of the case where there's an array of objectids that happens to contain a number.
