### ISSUE TITLE
BUG: unsupported deep lean with `true`

### ISSUE THREAD

**Issue by picnixz** [vkarpov15/mongoose-lean-virtuals#47]
**Do you want to request a *feature* or report a *bug*?** 

I would like to report a bug in that library.

**Steps to reproduce.**

```ts
'use strict'

import assert from 'assert'
import mongoose from 'mongoose'

(async () => {
  try {
    await mongoose.connect('mongodb://localhost:27017/test', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
      useFindAndModify: false
    })
    
    const plugin = require('mongoose-lean-virtuals')
   
    const T1 = new mongoose.Schema({ t11: String }, { _id: false })
    T1.virtual('t12').get(() => 't12')
    T1.plugin(plugin)
    const T2 = new mongoose.Schema({ t1: T1, t2: String })
    T2.virtual('t21').get(() => 't21')
    T2.plugin(plugin)
    const MT2 = mongoose.model('MT2', T2)
    const reps = new MT2({ t1: { t11: 't11' }, t2: 't2' })
    await reps.save()
    const received = await MT2.findById(reps._id).lean({ virtuals: true }).exec()
    const expected = {
      _id: reps._id,
      id: reps._id.toString(),
      t1: { t11: 't11', t12: 't12' /* virtual */ },
      t2: 't2',
      t21: 't21' /* virtual */,
      __v:0
    }

    /* the following assertion fails */
    assert.deepStrictEqual(received, expected)
    process.exit(0)
  } catch (e) {
    console.info(e)
    process.exit(-1)
  }
})()
```

**Expected behaviour**

When passing `{ virtuals: true }`, I would expect that the plugin also applies this to sub-schemas, so that my above virtual field `t2.t21` is populated. I would even suggest adding another option, say `{ deep: true }` either for the `lean` (e.g. `lean({ virtuals: true, deep: true })`) or suggest a plugin option proper to the schema (e.g. `schema.plugin(require('mongoose-lean-virtuals'), { deep: true })`). We may even do both so that the option given to the `lean()` method overrides the one given to the plugin, although not sure whether it is possible with the current framework.

The problem arises from there [https://github.com/vkarpov15/mongoose-lean-virtuals/blob/f39b0a66a26432609124f47247400b7b30caca46/index.js#L115-L125](https://github.com/vkarpov15/mongoose-lean-virtuals/blob/f39b0a66a26432609124f47247400b7b30caca46/index.js#L115-L125) As you can see, when `virtuals` is set to `true`, then it does not consider the keys of `schema.virtuals`. 

EDIT: I removed my fix which is not an entirely correct fix. I will need to investigate more but this issue remains as is, I think.

**Versions**

Node.js: 10.21.0
Mongoose: 5.11.4
mongoose-lean-virtuals: 0.7.5
MongoDB: 4.4.2

**Comment by vkarpov15** [comment]
Fix is in v0.7.6, thanks :+1:
