### ISSUE TITLE
parent() documentation

### ISSUE THREAD

**Issue by Danijj89** [vkarpov15/mongoose-lean-virtuals#49]
I'm having the same exact issue as #40, but I wasn't able to find any documentation/example on how the parent() function is supposed to be used.

I would greatly appreciate it if you could point me to an example of how to use it.

Thanks

**Comment by vkarpov15** [comment]
Added an example here: https://github.com/vkarpov15/mongoose-lean-virtuals/blob/master/examples.md#it-lets-you-access-a-lean-subdocuments-parent
