### ISSUE TITLE
mongoose lean not overwrite

### ISSUE THREAD

**Issue by mxyue** [vkarpov15/mongoose-lean-virtuals#5]
mongoose(4.9.5) lean method is this
`
Query.prototype.lean = function(v) {

  this._mongooseOptions.lean = arguments.length ? !!v : true;

  return this;

};
`
lean function just get true or false, can't pass other params. 
It's not work for me

**Comment by vkarpov15** [comment]
Upgrade to [mongoose >= 4.11.0](https://github.com/Automattic/mongoose/blob/master/History.md#4110--2017-06-25)

**Comment by vkarpov15** [comment]
@mxyue can you provide a repro script?
