### ISSUE TITLE
Plugin usage with QueryCursor.eachAsync

### ISSUE THREAD

**Issue by nico29** [vkarpov15/mongoose-lean-virtuals#9]
Hello,

In our codebase we were doing 

```javascript
ourModel.find(OUR_QUERY)
   .lean({ virtuals: true })
   .cursor()
   .eachAsync(p => {
      // p is not a POJO but a Model instance
      // w/ save, update... methods
   });
```

Still as the comment in the callback suggest, `p` is not a POJO (and it should be as stated [here](https://github.com/Automattic/mongoose/issues/5097#issuecomment-289634555)).

This is not a bug related to this plugin since mongoose itselft checks the explicit `true` value of the lean options before hitting the `eachAsync` callback ([here](https://github.com/Automattic/mongoose/blob/master/lib/cursor/QueryCursor.js#L271)).

Should the verification done by mongoose check the truthyness of the lean option instead of the explicit `true` value ? 
Or should this be marked as the expected behavior in the documentation of this plugin ?

Also how to get the virtuals in the async w/ the `lean` 🤔  (dropping the `lean` and using `.toObject()` works, but it makes no use of the `lean` feature...) 

In any case, I'ld be glad to help :)

Thank you.

**edit**: checking the truthyness in mongoose would not help because the `.cursor` method does not trigger post find hooks, which this plugin relies on.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate. Opened up an issue in Mongoose to track

**Comment by nico29** [comment]
Thank you @vkarpov15 ! 🍪
